name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 3 : Construire et pousser l'image Docker
      - name: Build and Push Docker Image
        run: |
          docker build -t gedeonm/docker-app:latest .
          docker push gedeonm/docker-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-docker

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            docker pull gedeonm/docker-app:latest
            docker stop angular-app || true
            docker rm angular-app || true
            docker run -d -p 80:80 --name angular-app gedeonm/docker-app:latest
